# Generated by Django 4.0.3 on 2022-04-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_attr_product_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='exists',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='attr_product',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
