# Generated by Django 4.0.3 on 2022-04-14 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attr_product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='attr_product',
            name='quantity',
        ),
        migrations.CreateModel(
            name='Features_price_effective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('color', 'رنگ'), ('size', 'اندازه')], default='color', max_length=10)),
                ('value', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('D', 'Dropdown'), ('C', 'checkbox')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
