# Generated by Django 4.0.3 on 2022-04-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_name_fa',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت پایه '),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.BooleanField(default=False, verbose_name='نوع کالا /پیچیده یا ساده '),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد کل محصول '),
        ),
    ]
