# Generated by Django 4.0.3 on 2022-04-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_brand_name_en_product_brand_name_fa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='features_price_effective',
            name='colorname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
